server:
  port: 9530
spring:
  application:
    name: nacos-consumer
  cloud:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1